/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsageImport } from './routes/usage'
import { Route as IndexImport } from './routes/index'
import { Route as LlmModelImport } from './routes/llm-model.'

// Create/Update Routes

const UsageRoute = UsageImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LlmModelRoute = LlmModelImport.update({
  id: '/llm-model/',
  path: '/llm-model/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageImport
      parentRoute: typeof rootRoute
    }
    '/llm-model/': {
      id: '/llm-model/'
      path: '/llm-model'
      fullPath: '/llm-model'
      preLoaderRoute: typeof LlmModelImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/usage': typeof UsageRoute
  '/llm-model': typeof LlmModelRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/usage': typeof UsageRoute
  '/llm-model': typeof LlmModelRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/usage': typeof UsageRoute
  '/llm-model/': typeof LlmModelRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/usage' | '/llm-model'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/usage' | '/llm-model'
  id: '__root__' | '/' | '/usage' | '/llm-model/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsageRoute: typeof UsageRoute
  LlmModelRoute: typeof LlmModelRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsageRoute: UsageRoute,
  LlmModelRoute: LlmModelRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/usage",
        "/llm-model/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/usage": {
      "filePath": "usage.tsx"
    },
    "/llm-model/": {
      "filePath": "llm-model..tsx"
    }
  }
}
ROUTE_MANIFEST_END */
